- name: disabling nodejs previous version
  ansible.builtin.command: dnf module disable nodejs -y

- name: enabled nodejs preffered version
  ansible.builtin.command: dnf module enable nodejs:20 -y
    
- name: installing nodejs
  ansible.builtin.dnf: # only works for Redhat family
    name: nodejs
    state: latest

- name: installing mysql
  ansible.builtin.dnf: # only works for Redhat family
    name: mysql
    state: latest

# - name: install nodejs dependensies
#   ansible.builtin.dnf: # only works for Redhat family
#     name: "{{ item }}"
#     state: installed
#   loop:
#   - nodejs
#   - mysql

- name: adding user
  ansible.builtin.user:
    name: expense
    state: present

- name: we are using common code
  ansible.builtin.import_role:
    name: common  ### here you meniton the common folder name ## the folder name you mention whatever you want, ( common ) is not a mandatory name
    tasks_from: app-pre-requisite ## (.yaml ) not required ## you mention file name where code is exist

# - name: downloading backend.zip  
#   ansible.builtin.get_url:
#     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
#     dest: /tmp/backend.zip

# - name: create a directory
#   ansible.builtin.file:
#     path: /app
#     state: directory

# - name: unzip the code
#   ansible.builtin.unarchive: 
#     src: /tmp/backend.zip
#     dest: /app
#     remote_src: yes  # remote_src: yes → file is already on the target server  # remote_src: no → file is on your Ansible control machine

- name: install npm dependencies
  ansible.builtin.command: npm install ## This npm dependencies we must install in the backend/code where it is unzipped
  args:
    chdir: /app

- name: copy a file backend.service.j2
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service

- name: daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: enable backend service
  ansible.builtin.service:
    name: backend
    enabled: yes

- name: installing python mysql dependensies
  ansible.builtin.pip:
    name:
    - PyMySQL
    - cryptography  ## this is for enter our passwords in commandline
    executable: pip3.9 # pip3.11 if python version is 3.11  3.9.18

- name: loading/dump/import the data into the mysql
  community.mysql.mysql_db:
    login_user: "{{ login_user }}"
    login_password: "{{ db_password }}"
    login_host: "{{ login_host_name }}"
    target: /app/schema/backend.sql
    state: import
    name: all

- name: start and enable backend service
  ansible.builtin.service:
    name: backend
    state: started
    
